kind: Service
apiVersion: v1
metadata:
  name: house-pricing-server
spec:
  selector:
    app: house-pricing-server
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort
