apiVersion: v1
kind: Pod
metadata:
  name: house-pricing-server
  labels:
    app: house-pricing-server
spec:
  containers:
    - name: house-pricing-server
      image: sadleader/house-pricing-server:v1
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"
      #livenessProbe:
      #httpGet:
      #path: /healthz
      #port: 5000
